aux_loss: true
backbone: resnet101
batch_size: 1
bbox_loss_coef: 5
track_prev_frame: 5
clip_max_norm: 0.1
coco_panoptic_path: null
coco_path: null
crowdhuman_path: data/CrowdHuman
crowdhuman_prev_frame_rnd_augs: 0.05
crowdhuman_train_split: null
dataset: mot
debug: false
dec_layers: 6
device: cuda
dice_loss_coef: 1
dilation: false
dim_feedforward: 2048
dist_backend: nccl
dist_url: file:///checkpoint/timmein/experiments/49d9bb36043d475aaeb1f212cb18e4be_init
distributed: true
dropout: 0.1
enc_layers: 6
eos_coef: 0.1
epochs: 180
eval: false
freeze_detr: false
giou_loss_coef: 2
gpu: 7
hidden_dim: 256
job_dir: !!python/object/apply:pathlib.PosixPath
- /
- checkpoint
- timmein
- experiments
- '%j'
load_mask_head_from_model: null
lr: 1.0e-06
lr_backbone: 1.0e-06
lr_drop: 500
lr_track: 1.0e-06
mask_loss_coef: 1
masks: true
mot17det_crowdhuman_image_scale: 1.0
mot17det_path: data/MOTS20
ngpus: 8
nheads: 8
no_vis: false
nodes: 4
num_queries: 100
num_workers: 2
output_dir: !!python/object/apply:pathlib.PosixPath
- models
- mot17det_train_mots_track_bbox_proposals_pretrain_train_mots_vis_mask_head
position_embedding: sine
pre_norm: false
rank: 31
resume: models/mot17det_train_mots_vis_track_bbox_proposals_track_encoding_bbox_proposals_prev_frame_5_mask_head/checkpoint_best_MASK_AP_IoU_0_50.pth
resume_optim: false
resume_vis: false
seed: 42
set_cost_bbox: 5
set_cost_class: 1
set_cost_giou: 2
similarity_frame: false
similarity_loss_coef: 1.0
similarity_margin: 1.0
slurm_comment: CVPR2020
slurm_constraint: volta32gb
slurm_partition: priority
start_epoch: 0
timeout: 4320
tracking: true
tracking_eval: true
track_attention: true
track_query_false_negative_prob: 0.1
track_query_false_positive_eos_weight: true
track_query_false_positive_prob: 0.1
track_query_noise: 0.0
train_split: train_mots
val_interval: 2
val_split: train_mots
vis_and_log_interval: 50
vis_port: 8888
vis_server: http://devfair0191
weight_decay: 0.0001
world_size: 32
deformable: false
img_transform:
  max_size: 1333
  val_width: 800
cls_loss_coef: 1.0
focal_alpha: 0.25
focal_loss: False
num_feature_levels: 1
multi_frame_attention: false
multi_frame_attention_separate_encoder: false
merge_frame_features: false
multi_frame_encoding: false
focal_alpha: 0.25
focal_gamma: 2
focal_loss: false
overflow_boxes: false
track_backprop_prev_frame: true
two_stage: false