aux_loss: true
backbone: resnet50
batch_size: 2
bbox_loss_coef: 5.0
clip_max_norm: 0.1
cls_loss_coef: 2.0
coco_and_crowdhuman_prev_frame_rnd_augs: 0.2
coco_panoptic_path: null
coco_path: data/coco_2017
crowdhuman_path: data/CrowdHuman
crowdhuman_train_split: train_val
dataset: mot_crowdhuman
debug: false
dec_layers: 6
dec_n_points: 4
deformable: true
device: cuda
dice_loss_coef: 1.0
dilation: false
dim_feedforward: 1024
dist_backend: nccl
dist_url: file:///storage/slurm/meinhard/runs/ad4f7798c3f04625871d1f191f8e6c9f_init
distributed: true
dropout: 0.1
enc_layers: 6
enc_n_points: 4
eos_coef: 0.1
epochs: 70
eval_only: false
eval_train: false
focal_alpha: 0.25
focal_gamma: 2
focal_loss: true
freeze_detr: false
giou_loss_coef: 2
gpu: 0
hidden_dim: 288
img_transform: !!python/object:argparse.Namespace
  max_size: 1333
  val_width: 800
load_mask_head_from_model: null
lr: 0.0002
lr_backbone: 2.0e-05
lr_backbone_names:
- backbone.0
lr_drop: 10
lr_linear_proj_mult: 0.1
lr_linear_proj_names:
- reference_points
- sampling_offsets
lr_track: 0.0001
mask_loss_coef: 1.0
masks: false
mot_path_train: data/MOT17
mot_path_val: data/MOT17
nheads: 8
no_vis: false
num_feature_levels: 4
num_queries: 500
num_workers: 2
output_dir: !!python/object/apply:pathlib.PosixPath
- /
- storage
- user
- meinhard
- fair_track
- models
- mot_crowdhuman_mot17_train_num_queries_500_batch_size=2_num_gpus_7_num_classes_20_AP_det_overflow_boxes_True_prev_frame_rnd_augs_0_2_uniform_false_negative_prob_num_classes_20_multi_frame_hidden_dim_288_sep_encoders_batch_queries_lr_drop_10
overflow_boxes: true
overwrite_lr_scheduler: false
overwrite_lrs: false
position_embedding: sine
pre_norm: false
rank: 0
resume: /storage/user/meinhard/fair_track/models/mot_crowdhuman_mot17_train_num_queries_500_batch_size=2_num_gpus_7_num_classes_20_AP_det_overflow_boxes_True_prev_frame_rnd_augs_0_2_uniform_false_negative_prob_num_classes_20_multi_frame_hidden_dim_288_sep_encoders_batch_queries_lr_drop_10/checkpoint.pth
resume_optim: true
resume_shift_neuron: false
resume_vis: true
save_model_interval: 5
seed: 43
set_cost_bbox: 5.0
set_cost_class: 2.0
set_cost_giou: 2.0
start_epoch: 1
track_attention: false
track_backprop_prev_frame: false
track_prev_frame_range: 5
track_prev_frame_rnd_augs: 0.01
track_prev_prev_frame: false
track_query_false_negative_prob: 0.4
track_query_false_positive_eos_weight: true
track_query_false_positive_prob: 0.1
tracking: true
tracking_eval: true
train_split: mot17_train_coco
two_stage: false
val_interval: 5
val_split: mot17_train_coco
vis_and_log_interval: 50
vis_port: 8092
vis_server: http://srvcremers2
weight_decay: 0.0001
with_box_refine: true
world_size: 7
multi_frame_attention: true
multi_frame_attention_separate_encoder: true
merge_frame_features: false
multi_frame_encoding: true
